project:
  type: book
  output-dir: ../experiments/book

book:
  title: "Experiments"
  author: "Witek ten Hove"
  date: "7/30/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - xgboost-pairwise-ranking.qmd
    - xgboost-objective-calc.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

